- hosts: k8s
  become: true
  tasks: 
  - name: copy deployment file to kubernetes master
    copy:
      src: myapp.yml
      dest: /root/
  - name: delete the previous kubernetes objects
    command: kubectl delete -f /root/myapp.yml
  - name: create a deployment by reading the definition from a local file
    command: kubectl apply -f /root/myapp.yml
